// <auto-generated />
namespace SPG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tag_Value_Stringified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tag_Value_Stringified));
        
        string IMigrationMetadata.Id
        {
            get { return "201802072216504_Tag_Value_Stringified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
