// <auto-generated />
namespace SPG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_VenueCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_VenueCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201802072200364_Added_VenueCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
