// <auto-generated />
namespace SPG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Prefixes_And_Suffixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prefixes_And_Suffixes));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101539063_Prefixes_And_Suffixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
