// <auto-generated />
namespace SPG.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Venue_Relation_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Venue_Relation_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "201802072341536_User_Venue_Relation_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
